all:
	javac -cp .:/home/gesposito/junit/src:junit-4.12.jar:hamcrest-core-1.3.jar CalcTest.java -Xlint


test2:
	javac -cp .:/home/gesposito/junit/src CalcTrial.java
rntest2:
	java -cp /home/gesposito/junit/src: CalcTrial


test:
	java -cp /home/gesposito/junit/src:junit-4.12.jar:hamcrest-core-1.3.jar: org.junit.runner.JUnitCore CalcTest
