all:  testjava  Deck Colltest Azhldm

testjava: testjava.java
	javac testjava.java

Deck: Deck.java
	javac Deck.java

Colltest: Colltest.java
	javac Colltest.java

Azhldm: Azhldm.java
	javac Azhldm.java

clean:
	rm -f *.class
