all:
	javac -cp ".:/home/gesposito/cs335/cs335/azholdm3/src:junit-4.12.jar:hamcrest-core-1.3.jar" PokerHandTest.java -Xlint

run:
	java -cp /home/gesposito/cs335/cs335/azholdm3/src:junit-4.12.jar:hamcrest-core-1.3.jar: org.junit.runner.JUnitCore PokerHandTest
