all:
	javac -cp .:/home/gesposito/cs335/cs335/azholdm3/src Game.java
	javac -cp .:/home/gesposito/cs335/cs335/azholdm3/src CollTest.java -Xlint


run:
	java -cp /home/gesposito/cs335/cs335/azholdm3/src: Game

run2:
	java -cp /home/gesposito/cs335/cs335/azholdm3/src: CollTest
