all:
	javac -cp .:/home/gesposito/cs335/azholdm2/src Game.java
	javac -cp .:/home/gesposito/cs335/azholdm2/src CollTest.java


run:
	java -cp /home/gesposito/cs335/azholdm2/src: Game

run2:
	java -cp /home/gesposito/cs335/azholdm2/src: CollTest
